version: '3.9'

services:
  db:   
    container_name: postgres1
    image: postgres:alpine3.17
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - /data/redis/logs:/var/log
      - /data/redis/data:/root/redis

    environment:
      - POSTGRES_PASSWORD=password

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  nexus:
    # image: sonatype/nexus3:3.60.0
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - 8081:8081
    restart: always
    volumes:
      - "/data/nexus/:/nexus-data"
      - nexus-vol:/opt/sonatype
volumes:
    nexus-vol:


